before:
  hooks:
    - go mod tidy
builds:
  - main: main.go
    id: rsvp_pizza
    binary: usr/local/bin/rsvp.pizza
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - main: cmd/renew_calendar_credentials.go
    id: renew_calendar_credentials
    binary: usr/local/bin/renew_calendar_credentials
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    rlcp: true
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      _{{ .Version }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    builds:
    - rsvp_pizza
    - renew_calendar_credentials
    files:
      - src: static/**/*
        dst: etc/pizza
        info:
          owner: pizza
          group: pizza
          mode: 0644
      - src: configs/nginx.conf
        dst: etc/pizza/nginx.conf
        info:
          owner: root
          group: root
          mode: 0644
      - src: configs/pizza.yaml
        dst: etc/pizza/pizza.yaml
        info:
          owner: pizza
          group: pizza
          mode: 0600
      - src: configs/.env
        dst: /etc/pizza/.env
        info:
          owner: root
          group: root
          mode: 0600
      - src: configs/pizza.service
        dst: etc/systemd/system/pizza.service
        info:
          owner: root
          group: root
          mode: 0644

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
